### ISSUE TITLE
How to enable HTTPS/TLS?

### ISSUE THREAD

**Issue by rileyhun** [navikt/opendistro-elasticsearch#10]
Hello,

Was wondering if it is possible to enable HTTPS in the helm chart? I tried setting SSL.HTTP is "true" but I don't think it did anything. 

Thanks!

**Comment by tuantrannav** [comment]
Hi,

You can enable https by using odfe.ssl.http.enabled: "true", put this in the values.yaml file. Remember to use trusted certs if you turn on https.
