### ISSUE TITLE
ElasticSearch Data & Master Pods are Unschedulable

### ISSUE THREAD

**Issue by rileyhun** [navikt/opendistro-elasticsearch#9]
Hello,

I am trying to deploy a production-ready OpenDistro deployment and I found your repo more helpful than the official helm chart from OpenDistro-Build. Unfortunately, I'm experiencing some trouble with the deployment after running your series of scripts sequentially. 

The data and master pods are unschedulable. Any help would be greatly appreciated! I think the error is due to: 

`Can’t schedule Pods because of missing Persistent Volume Claims.`

<img width="1008" alt="Screen Shot 2021-03-17 at 12 42 51 AM" src="https://user-images.githubusercontent.com/20649466/111432282-0cb29000-86ba-11eb-96fe-7c6898e7c823.png">

**Comment by tuantrannav** [comment]
Hi thank you for your comment, is it possible if you could copy and paste the logs from the container?

**Comment by tuantrannav** [comment]
by default the PVC runs on docker-deskstop "hostpath" storage class, if you run on a different storage you need to change that.

**Comment by rileyhun** [comment]
Thanks so much for the fast response! Really appreciate it. I made the switch to my custom storage class on GCP. Now I'm getting these errors:

<img width="1104" alt="Screen Shot 2021-03-17 at 9 52 38 AM" src="https://user-images.githubusercontent.com/20649466/111506227-a869ed80-8706-11eb-8de4-c19d2e65ff70.png">
<img width="1104" alt="Screen Shot 2021-03-17 at 9 51 59 AM" src="https://user-images.githubusercontent.com/20649466/111506241-ad2ea180-8706-11eb-856f-838374667b2d.png">
